### ISSUE TITLE
Strange result of scene_collision.py.

### ISSUE THREAD

**Issue by DangBowen-Bell** [markomih/COAP#5]
Hi, thank you for your code release of COAP. I meet some problems while running scene_collision.py

I follow the instructions of the tutorial and run scene_collision.py using default parameters. However, the result looks a little strange:

![image](https://user-images.githubusercontent.com/35923383/211958829-c10959a2-2e90-4df0-97ee-95efc185a5dc.png)

I see that the script only optimizes the position of the body. So I add the body pose and run again. But the result is worse:

![image](https://user-images.githubusercontent.com/35923383/211958209-f822deef-d6b3-4244-8904-702a9522be43.png)

The collision does not exist after optimization. However, the position and pose is very strange. I want to know if the result is normal or should I modify some code to improve the result? (For example, add some regularization term to constrain the position and pose)

Looking forward to your reply!

**Comment by markomih** [comment]
Hi @DangBowen-Bell,

I appreciate your interest in our project. Indeed the collision loss can lead to an invalid body if the loss term is used without other regularizations. 
Note that most prior works use a combination of loss terms to further constrain the optimization (keypoints, pose priors, etc.). You could check other more comprehensive pipelines to get an idea (e.g. PROX, LEMO, etc.) 

Best,
Marko

**Comment by DangBowen-Bell** [comment]
Ok, I see.  I will do some experiments with other regularization terms. 

Thank you for your reply.
